// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2Clij2yk3HrW5JH6cri_v83TMP__wHqc',
    appId: '1:649352763169:web:1fa259ce6d359ed1bc9060',
    messagingSenderId: '649352763169',
    projectId: 'flutter-authentication-dbbcd',
    authDomain: 'flutter-authentication-dbbcd.firebaseapp.com',
    storageBucket: 'flutter-authentication-dbbcd.appspot.com',
    measurementId: 'G-RX7FK429MZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCG_k1zYuICys0IgVVxkgg_Hk6-ROWG-j8',
    appId: '1:649352763169:android:7266b6bfd9651619bc9060',
    messagingSenderId: '649352763169',
    projectId: 'flutter-authentication-dbbcd',
    storageBucket: 'flutter-authentication-dbbcd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5QJpX5WYT4mt91l-TxLT5h_A5Rchk0Po',
    appId: '1:649352763169:ios:66ed408696d809eabc9060',
    messagingSenderId: '649352763169',
    projectId: 'flutter-authentication-dbbcd',
    storageBucket: 'flutter-authentication-dbbcd.appspot.com',
    iosBundleId: 'com.example.musicplayer2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5QJpX5WYT4mt91l-TxLT5h_A5Rchk0Po',
    appId: '1:649352763169:ios:7503704d1ef09dedbc9060',
    messagingSenderId: '649352763169',
    projectId: 'flutter-authentication-dbbcd',
    storageBucket: 'flutter-authentication-dbbcd.appspot.com',
    iosBundleId: 'com.example.musicplayer2.RunnerTests',
  );
}
